name = "dijkstra"
version = "0.1.0"

description = "A versatile implementation of Dijkstra's shortest path algorithm for Gleam."
licences = ["Apache-2.0"]
repository = { type = "github", user = "hraftery", repo = "gleam-dijkstra" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleamy_structures = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
